html/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::match(['GET', 'POST'], 'forget-password', ['as' => 'webForgetPassword', 'uses' => 'UserController@doForgetPassword']);
Route::get('/cart_redirect_page', function () {
    return view('payment_cart_redirect');
});

html/app/Booking.php
<?php

namespace App;

use Carbon\Carbon;
use DateTimeInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Booking extends Model
{
    use SoftDeletes;
    protected $table = 'trx_booking';

    protected $hidden = [
        'deleted_at'
    ];
    protected $guarded = [
        'id'
    ];

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function details()
    {
        return $this->hasMany('App\BookingDetail');
    }

    public function getTotalDetails()
    {
        return $this->details()->count();
    }

    public function payment()
    {
        return $this->hasOne('App\Payment');
    }

    public function deliveryPoint()
    {
        return $this->hasOne('App\DeliveryPoint', 'id', 'booking_delivery_point_id');
    }

    public function subConsole()
    {
        return $this->hasOne('App\User', 'id', 'booking_delivery_point_id');
    }

    public function validInfo()
    {
        return $this->hasOne('App\SubConsoleTransaction', 'booking_id', 'id');
    }

    public function shipment()
    {
        return $this->hasOne('App\AJCBookingLog');
    }

    public function exceed()
    {
        return $this->hasOne('App\BookingExceed', 'booking_id', 'id');
    }

    public function getBookingCodeAttribute($value)
    {
        return strtoupper($value);
    }

    public function paymentRequest()
    {
        return $this->hasMany('App\PaymentRequest', 'booking_id', 'id');
    }

    public function cart()
    {
        //return $this->hasOne('App\PaymentCart', 'booking_id', 'id');
        return $this->hasOne('App\PaymentCart', 'booking_id', 'id')->where('cart_status',1); //20210323 - TID: U9LgjemB - KIBAR
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    //20210224 - TID: 3B23WByr - START
    public function voucher_usage()
    {
        return $this->hasOne('App\VoucherUsage', 'id', 'booking_id');
    }

    public function voucher()
    {
        return $this->hasOne('App\VourcherData', 'id', 'voucher_id');
    }
    //20210224 - TID: 3B23WByr - END

    public function service()
    {
        return $this->hasOne('App\ServiceType', 'alias', 'service_type');
    }

}

html/resources/views/payment_cart_paid.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Informasi Pembayaran</title>
    <style>
		html {
			height: 100%;
			background-image: url('{{ Storage::url('artwork/ka-pattern.png') }}');
			/* background-position: center; */
			background-repeat: no-repeat;
			background-size: cover;
		}
        body {
            background-color: transparent;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5 mb-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Informasi Pembayaran
                    </div>
                    <div class="card-body">
                        
                        <h3 class="card-title text-success">Sudah Lunas! Terima kasih.</h3>

                        <p class="card-text">{{date('d M Y g:i A', strtotime($bookings[0]->payment->paid_at))}}</p>
                        
                        <h5>Rincian Pengiriman</h5>
                        @php
                            $amount = 0;
                            $tax = 0;
                        @endphp
                        @foreach ($bookings as $booking)
                        <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{strtoupper($booking->booking_code)}}</h5>
                                </div>
                                <p class="mb-1">
                                    {{ $booking->booking_origin_name }} ({{ $booking->booking_origin_phone }})<br>
                                    {{ $booking->booking_origin_addr_1 }} - {{ $booking->booking_origin_city }}
                                </p>
                                <hr>
                                <p class="mb-1">
                                    {{ $booking->booking_destination_name }} ({{ $booking->booking_destination_phone }})<br>
                                    {{ $booking->booking_destination_addr_1 }} - {{ $booking->booking_destination_city }}
                                </p>
                            </a>
                        </div>  
                        @php
                            $amount += $booking->payment->transaction_amount;
                            $tax += $booking->payment->transaction_tax;
                        @endphp  
                        @endforeach

                        {{-- <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">KODE-BOOKING</h5>
                                    
                                </div>
                                <p class="mb-1">
                                    Andri (08117777804)<br>
                                    Jalan M1 - TANGERANG KOTA, KOTA. TANGERANG, BANTEN, INDONESIA
                                </p>
                                <hr>
                                <p class="mb-1">
                                    Joko (085157810804)<br>
                                    Jalan Apa Aja - NONGSA, KOTA. BATAM, KEPULAUAN RIAU, INDONESIA
                                </p>
                            </a>
                        </div>

                        <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">KODE-BOOKING</h5>
                                    
                                </div>
                                <p class="mb-1">
                                    Andri (08117777804)<br>
                                    Jalan M1 - TANGERANG KOTA, KOTA. TANGERANG, BANTEN, INDONESIA
                                </p>
                                <hr>
                                <p class="mb-1">
                                    Joko (085157810804)<br>
                                    Jalan Apa Aja - NONGSA, KOTA. BATAM, KEPULAUAN RIAU, INDONESIA
                                </p>
                            </a>
                        </div> --}}

                        <h5 class="mt-4">Rincian Biaya</h5>
                        <dl class="row">
                            <dt class="col-sm-3">Biaya Kirim</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($amount) }}</dd>
                            <dt class="col-sm-3">Pajak Kirim</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($tax) }}</dd>
                            <dt class="col-sm-3">Total</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($amount+$tax) }}</dd>
                        </dl>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</body>

</html>

html/resources/views/payment_cart_redirect.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Informasi Pembayaran</title>
    <style>
		html {
			height: 100%;
			background-image: url('{{ Storage::url('artwork/ka-pattern.png') }}');
			/* background-position: center; */
			background-repeat: no-repeat;
			background-size: cover;
		}
        body {
            background-color: transparent;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5 mb-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Informasi Pembayaran
                    </div>
                    <div class="card-body">
                        
                        @if ($success)
                        <h3 class="card-title text-success">Pembayaran Berhasil</h3>
                        @else
                        <h3 class="card-title text-danger">Pembayaran Gagal</h3>
                        @endif

                        <p class="card-text">{{$paidDate}}<br>{{$paidAt}}</p>
                        
                        <h5>Rincian Pengiriman</h5>
                        @php
                            $amount = 0;
                            $tax = 0;
                        @endphp
                        @foreach ($bookings as $booking)
                        <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{strtoupper($booking->booking_code)}}</h5>
                                </div>
                                <p class="mb-1">
                                    {{ $booking->booking_origin_name }} ({{ $booking->booking_origin_phone }})<br>
                                    {{ $booking->booking_origin_addr_1 }} - {{ $booking->booking_origin_city }}
                                </p>
                                <hr>
                                <p class="mb-1">
                                    {{ $booking->booking_destination_name }} ({{ $booking->booking_destination_phone }})<br>
                                    {{ $booking->booking_destination_addr_1 }} - {{ $booking->booking_destination_city }}
                                </p>
                            </a>
                        </div>  
                        @php
                            $amount += $booking->payment->transaction_amount;
                            $tax += $booking->payment->transaction_tax;
                        @endphp  
                        @endforeach

                        {{-- <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">KODE-BOOKING</h5>
                                    
                                </div>
                                <p class="mb-1">
                                    Andri (08117777804)<br>
                                    Jalan M1 - TANGERANG KOTA, KOTA. TANGERANG, BANTEN, INDONESIA
                                </p>
                                <hr>
                                <p class="mb-1">
                                    Joko (085157810804)<br>
                                    Jalan Apa Aja - NONGSA, KOTA. BATAM, KEPULAUAN RIAU, INDONESIA
                                </p>
                            </a>
                        </div>

                        <div class="list-group mt-3">
                            <a href="#" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">KODE-BOOKING</h5>
                                    
                                </div>
                                <p class="mb-1">
                                    Andri (08117777804)<br>
                                    Jalan M1 - TANGERANG KOTA, KOTA. TANGERANG, BANTEN, INDONESIA
                                </p>
                                <hr>
                                <p class="mb-1">
                                    Joko (085157810804)<br>
                                    Jalan Apa Aja - NONGSA, KOTA. BATAM, KEPULAUAN RIAU, INDONESIA
                                </p>
                            </a>
                        </div> --}}

                        <h5 class="mt-4">Rincian Biaya</h5>
                        <dl class="row">
                            <dt class="col-sm-3">Biaya Kirim</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($amount) }}</dd>
                            <dt class="col-sm-3">Pajak Kirim</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($tax) }}</dd>
                            <dt class="col-sm-3">Total</dt>
                            <dd class="col-sm-9 text-right">IDR {{ number_format($amount+$tax) }}</dd>
                        </dl>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</body>

</html>

html/resources/views/payment_cart_redirect_va.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Informasi Pembayaran</title>
    <style>
		html {
			height: 100%;
			background-image: url('{{ Storage::url('artwork/ka-pattern.png') }}');
			/* background-position: center; */
			background-repeat: no-repeat;
			background-size: cover;
		}
        body {
            background-color: transparent;
        }

        @media (min-width:800px) {
            #link-web {
                display: block;
            }
        }
    </style>
    <script>
        function copyVA() {
            /* Get the text field */
            var copyText = document.getElementById('virtualAccountNo');
            var textArea = document.createElement("textarea");
            textArea.value = copyText.textContent;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand("Copy");
            textArea.remove();
            document.getElementById("copyVirtualAccount").value = "Tersalin";
        }

        function copyAmount() {
            /* Get the text field */
            var copyText = document.getElementById("totalAmount");
            var textArea = document.createElement("textarea");
            textArea.value = copyText.textContent.replace(',','');
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand("Copy");
            textArea.remove();
            document.getElementById("copyTotalAmount").value = "Tersalin";
        }
    </script>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5 mb-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Informasi Pembayaran
                        <a href="https://kirimaja.id/" style="display:none;float:right" id="link-web">🏠</a>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title text-success">Menunggu Pembayaran</h3>
                        <p class="card-text">{{$paidDate}}<br>{{$paidAt}}</p>

                        <h5></h5>
                        <div class="card text-white bg-success mb-2">
                            <div class="card-header">Tagihan Anda Saat Ini</div>
                            <div class="card-body">
                                <h4 class="card-title">{{ $provider ?? '' }} - Virtual Account<br><span id="virtualAccountNo">{{ $virtualNo ?? '' }}</span></h4>
                                <button id="copyVirtualAccount" type="button" class="btn btn-outline-light btn-sm" onclick="copyVA()">Salin Virtual Account</button>
                                <p class="card-text mt-2">
                                    <h3>IDR <span id="totalAmount">{{ number_format($amount) }}</span></h3>
                                    <button id="copyTotalAmount" type="button" class="btn btn-outline-light btn-sm" onclick="copyAmount()">Salin Tagihan</button>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>

</html>

html/resources/views/payment_charge.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Charge Payment</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
<!-- 7982 -->

    <form id="paymentForm" action="{{$dokuPay}}" method="post">
        <input type="hidden" name="MALLID" value="7982">
        <input type="hidden" name="CHAINMERCHANT" value="NA">
        <input type="hidden" name="AMOUNT" value="{{$amount}}">
        <input type="hidden" name="PURCHASEAMOUNT" value="{{$amount}}">
        <input type="hidden" name="TRANSIDMERCHANT" value="{{$transId}}">
        <input type="hidden" name="WORDS" value="{{$words}}">
        <input type="hidden" name="REQUESTDATETIME" value="{{$requestDate}}">
        <input type="hidden" name="CURRENCY" value="360">
        <input type="hidden" name="PURCHASECURRENCY" value="360">
        <input type="hidden" name="SESSIONID" value="{{$transId}}">
        <input type="hidden" name="NAME" value="{{$name}}">
        <input type="hidden" name="EMAIL" value="{{$email}}">
        <input type="hidden" name="MOBILEPHONE" value="{{$mobile}}">
        <input type="hidden" name="BASKET" value="{{$basket}}">
    </form>
    <script>
        $(document).ready(function () {
            $('#paymentForm').submit();
        });
    </script>
</body>
</html>

html/resources/views/payment_option.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Payment Option</title>
    <style>
        /* @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,700'); */

        body {
            background-color: #a9a9a9;
            background-size: 100% auto;
            font-family: 'Roboto', Helvetica, sans-serif;
            letter-spacing: 0.05em;
        }

        .container {
            max-width: 350px;
            margin: 100px auto;
        }

        .card {
            background-color: #fff;
            text-transform: uppercase;
            border-radius: 4px;
            box-shadow: 0 20px 40px 0 #42472B, 0 2px 4px 0 rgba(0, 0, 0, 0.19);
        }

        a {
            text-decoration: none;
            color: #333;
        }

        .title {
            padding: 10px;
            text-align: center;
        }

        .title h1 {
            font-size: 16px;
            color: #333;
            font-weight: normal;

        }

        .item {
            border-top: solid 1.5px #f1f1f1;
            padding: 0px 20px;
            background-color: #fff;
            transition: background-color ease 240ms;
            font-size: 11px;
            padding: 18px 20px 15px 20px;

        }

        .item:hover {
            background-color: #f6f6f6;
        }

        .item-image {
            width: 40px;
            height: 30px;
            display: inline-block;
            margin-right: 10px;
            vertical-align: middle;
        }

        .item-text {
            display: inline-block;
            padding-bottom: 10px;
        }

        .item-selected {
            background-color: #f6f6f6;
            position: relative;
        }

        .button {
            padding: 20px;
            background-color: #598BDD;
            border-radius: 0px 0px 4px 4px;
            color: #fff;
            text-align: center;
            transition: background-color ease 240ms;
            font-size: 13px;
        }

        .button:hover {
            background-color: #4E7CC7;
            transform: translateY(1px);
        }

        .check {
            position: absolute;
            right: 20px;
            top: 20px;
        }

        .arrow {
            display: inline-block;
            vertical-align: bottom;
        }

        .dots-container {
            display: block;
            margin: 10px auto;
        }

        .dots {
            width: 10px;
            height: 10px;
            display: inline-block;
            margin: 0 0.125em;
            border-radius: 50%;
            background-color: #DEDEDE;
        }

        .dot-active {
            background-color: #AAAAAA;
        }

        .item-text span {
            margin-left: 10px;
            font-size: 10px;
            color: #fff;
            background-color: #a9a9a9;
            padding: 5px 10px;
            border-radius: 5px;
        }

        .item-text h4#copyVA {
            margin-top: 10px !important;
            padding: 10px 15px;
            font-size: 10px;
            color: #fff;
            background-color: #a9a9a9;            
            border-radius: 5px;
        }

        /* our own */
        button {
            font-size: 15px;
        }
        .mt-1 {
            margin-top: 0.4rem;
        }

        .mt-2 {
            margin-top: 0.8rem;
        }

        .item-text img {
            margin-top: 10px;
            width: 100%;
        }

        /* reset */
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            margin: 0px;
        }
        button.bg-gradient1 {
            margin: 0px;
            padding: 0px;
        }
        .bg-gradient1>span,
        .bg-gradient1:before {
            margin: 0px;
            background: #fa7e29;
            background: -webkit-gradient(linear, left top, left bottom, from(#83ABE0), color-stop(80%, #83ABE0), to(#83ABE0));
            background: linear-gradient(180deg, #83ABE0 0%, #83ABE0 80%, #83ABE0 100%);
        }
        .bg-gradient2>span,
        .bg-gradient2:before {
            margin: 0px;
            background: #83ABE0;
            background: -webkit-gradient(linear, left top, left bottom, from(#314251), color-stop(80%, #314251), to(#314251));
            background: linear-gradient(180deg, #314251 0%, #314251 80%, #314251 100%);
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img-preview')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
                $('#storeFile').show();
            }
        }

        $(document).ready(function () {
            $('#uploadFile').click(function (e) {
                e.preventDefault();
                $('#getFile').click();
            })
            // $('#storeFile').click(function (e) {
            //     e.preventDefault();
            //     $('#proofForm').submit();
            // })
            $('a#va_option').click(function (e) {
                e.preventDefault();
                $('.vitrual-account-info').show();
            })

            $('h4#copyVA').click(function (e) {
                console.log("clicked");
                
                // var copyVA = document.getElementById("va_account");
                // copyVA.select();
                // copyVA.setSelectionRange(0, 99999);

                // document.execCommand("copy");
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val("88554124242424").select();
                document.execCommand("copy");
                $temp.remove();
                $('h4#copyVA').text("Copied");
            });
        });
    </script>
</head>

<body>
    <div class="container">
        <div class="card">
            <div class="title">
                <h1>Metode Pembayaran</h1>
            </div>
            <a id="va_option" href="#">
                <div class="item">
                    <div class="item-text">
                        Virtual Account</div>
                </div>
            </a>
            <a href="#">
                <div class="item">
                    <div class="item-text">Kartu Debit atau Kredit<span>Belum Tersedia</span></div>
                </div>
            </a>

        </div>

        <div class="card mt-2 vitrual-account-info" hidden>
            <div class="title">
                <h1>Pembayaran Virtual Account</h1>
            </div>
            <a href="#">
                <div class="item">
                    <div class="item-text">
                        <h1>Bank Mandiri</h1>
                        <h1>88554124242424</h1>
                        <input id="va_account" type="hidden" name="va_account" value="88554124242424">
                        <h4 id="copyVA">Copy Virtual Account</h4>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="item">
                    <div class="item-text">
                        <form id="proofForm" action="" method="POST" enctype="multipart/form-data">
                            <!-- <button>Upload Bukti Bayar</button> -->
                            {{--  class="fancy-button pop-onhover bg-gradient1" --}}
                            {{-- class="fancy-button pop-onhover bg-gradient2" --}}
                            <button id="uploadFile">Upload Bukti Bayar</button>
                            <button id="storeFile" type="submit" hidden><span>Simpan</span></button>
                            <input type="file" id="getFile" name="proof_of_payment" onchange="readURL(this);" hidden>
                        </form>
                        <img id="img-preview" src="" alt="" />
                    </div>
                </div>
            </a>

        </div>
    </div>
</body>

</html>